spring.application.name=typeahead

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
app.redis.node2.host=${REDIS_NODE2_HOST:localhost}
app.redis.node2.port=${REDIS_NODE2_PORT:6380}
app.redis.node3.host=${REDIS_NODE3_HOST:localhost}
app.redis.node3.port=${REDIS_NODE3_PORT:6381}

server.port=8081

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/typeahead}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
